### ISSUE TITLE
Multiple H1 (A minor issue)

### ISSUE THREAD

**Issue by madsoulswe** [markwemekamp/RankOne-Umbraco-SEO-Tool#1]
Html 5 standard states that document can contain multiple h1, with some rules. 
The elements: **article**, **section**, **nav**, **aside** are section/content elements and can have a h1. =)

https://www.w3.org/TR/html-markup/h1.html
http://webdesign.tutsplus.com/articles/the-truth-about-multiple-h1-tags-in-the-html5-era--webdesign-16824

**Comment by markwemekamp** [comment]
You're right, I'm going to fix this as soon as possible. Thanks!

**Comment by markwemekamp** [comment]
I removed the heading analyzer for now since it's only purpose was to ensure at least 1 and prevent multiple h1 tags, maybe I'll add it in the future again with the correct implementation
