### ISSUE TITLE
CSS "bleeds" into umbraco

### ISSUE THREAD

**Issue by rasmusfjord** [markwemekamp/RankOne-Umbraco-SEO-Tool#11]
The css for rankone needs to be contained, it bleeds into other properties/datatypes. 

Maybe convert into a Scss file and wrap all in a .rankoneseotool class and add that to all the angular views. 

It bleeding into our custom datatypes, and teacommerces datatypes, as i noticed so far.

![image](https://cloud.githubusercontent.com/assets/1286043/20385019/15e3a070-acb6-11e6-9fa4-e936f7ce157e.png)

**Comment by markwemekamp** [comment]
Thanks for reporting
I'm definitely going to look into this, I'll keep you posted

**Comment by markwemekamp** [comment]
This should be fixed in the v0.3.5 I just uploaded to our and nuget
