### ISSUE TITLE
Still seems like it bleeds out 

### ISSUE THREAD

**Issue by rasmusfjord** [markwemekamp/RankOne-Umbraco-SEO-Tool#13]
Check the .pointer class here. Alot of stuff here is not encapsulated in a rankone class. 

![image](https://cloud.githubusercontent.com/assets/1286043/20565814/40f500b0-b193-11e6-9c48-d3fca09ac041.png)

**Comment by markwemekamp** [comment]
That's weird, I checked the content of the package (v0.3.5) and all classes are  prefixed with .rank-one.

Are you sure you installed the latest version? Maybe for some weird reason the css files weren't overwritten

![image](https://cloud.githubusercontent.com/assets/3817270/20569840/c65bbc72-b1a1-11e6-9fe2-fb781a1946c3.png)

**Comment by rasmusfjord** [comment]
yeah i see my nuget wasnt updating assets just the binaries, so deleted app_plugins and restored :)
