### ISSUE TITLE
v0.3.5 Dashboard rendering broken in Umbraco version 7.5.10

### ISSUE THREAD

**Issue by mfosterk80** [markwemekamp/RankOne-Umbraco-SEO-Tool#14]
It looks like something is broken, possibly in regard to the latest styles.css file (RankOne v 0.3.5), in Umbraco version 7.5.10.  Both overall site dashboard and individual document dashboards are affected.  All of the raw information displays, but the styling is wacked out.

Rolling back to RankOne v0.3.4 renders correctly in Umbraco 7.5.10.

**Comment by markwemekamp** [comment]
Thanks for reporting, I'll have a look

**Comment by markwemekamp** [comment]
I did a fresh umbraco 7.5.10 install with a nuget install of 0.3.5. I don't see any styling issues. Can you post a screenshot?

**Comment by mfosterk80** [comment]
Rats!  I thought about the screen shots right after I posted that issue and
realized I should have taken one.  I’ll update my local dev version back to
the latest and send some shots to you here in a few.  Hang on.

On March 2, 2017 at 8:22:51 AM, Mark (notifications@github.com) wrote:

I did a fresh umbraco 7.5.10 install with a nuget install of 0.3.5. I don't
see any styling issues. Can you post a screenshot?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/markwemekamp/RankOne-Umbraco-SEO-Tool/issues/14#issuecomment-283651734>,
or mute the thread

**Comment by mfosterk80** [comment]
Mark:

I just did a Nuget update on the site I was having issues with yesterday
and updated from 0.3.4 => 0.3.5 and it is showing everything as good.  So I
guess I owe you an apology for the hassle on this.
I can’t explain what was going on yesterday.  I messed around with this for
hours and 0.3.5 always displayed oddly.  In doing a file by file comparison
between the versions as well as using the browser inspector to look at and
compare the older live site with the local updated dev site, the only thing
I could really see that had changed dramatically was the style.css file,
which seemed to jibe with the behavior I was seeing.

Maybe I had some weird browser or server cache thing going on locally.

Anyway, sorry again for harshing your mellow with this.

Matt

On March 2, 2017 at 8:22:51 AM, Mark (notifications@github.com) wrote:

I did a fresh umbraco 7.5.10 install with a nuget install of 0.3.5. I don't
see any styling issues. Can you post a screenshot?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/markwemekamp/RankOne-Umbraco-SEO-Tool/issues/14#issuecomment-283651734>,
or mute the thread

**Comment by markwemekamp** [comment]
No problem Matt! If you encounter any strange things, don't hesitate to post it here :)

I'll close this issue for now
