### ISSUE TITLE
Just some typos

### ISSUE THREAD

**Issue by argentini** [markwemekamp/RankOne-Umbraco-SEO-Tool#16]
Great package! Thank you! Noticed a typo and a missing period. Thought I'd let you know for some future release.

"Title is longer than 60 characters, anything longer than 60 characters will be concatenated."
Should be...
"Title is longer than 60 characters. Anything longer than 60 characters will be truncated."

**Comment by markwemekamp** [comment]
Thanks for reporting, finally got the time to fix this :)
