### ISSUE TITLE
Package release

### ISSUE THREAD

**Issue by akeilox** [markwemekamp/RankOne-Umbraco-SEO-Tool#3]
Thank you for sharing this package.

For people without VS access, will there be a package update on the Umbraco Projects page?

**Comment by markwemekamp** [comment]
My pleasure!
Yes definitely, at the moment I'm testing new functionality which I'm planning to release as a package next week or maybe the week after.
It there functionality you are waiting for at the moment?

**Comment by akeilox** [comment]
Thats great to hear!

I have just read about the H1 tags on project page.
I initially came to the project page to see how to add the Meta data property editors.
Installing the package from projects' page on a clean 7.4.3 I cant seem to find the meta-data property editors to capture meta data. Managed to add the dashboard, summary and status properties but cant seem to locate the one with meta-data capturing.

**Comment by markwemekamp** [comment]
With meta data, you mean the following interface?

https://our.umbraco.org/media/wiki/154354/635996039060614166_compositionpng.png

To keep provide this functionality within the Umbraco philosophy, I haven't added this as a property editor but as doctype composition. You should be able to find this as a doctype and include it to other doctypes using the Compositions button

**Comment by akeilox** [comment]
Oh I see..

Having not used the document composition before, but tried when they first introduced without success, I didnt notice that.

Indeed there is a document composition under Templates, and added to document type. Thank you for clarifying that.

What is the designed/expected use case for the meta value within the template code, is it iterated like     @CurrentPage._seoMetaDescription
or simply
@CurrentPage.seoMetaKeywords

**Comment by markwemekamp** [comment]
@CurrentPage.SeoMetaKeywords should work

**Comment by markwemekamp** [comment]
Did you get the composition to work?

**Comment by akeilox** [comment]
yes! composition works great.

I opted to use 
meta @CurrentPage._seoMetaDescription
meta @CurrentPage._seoMetaKeywords

to traverse to the parent, if current page is empty - within the Master Template code.

Thanks again for sharing this great package! Looking forward to the new package release with updates.

**Comment by markwemekamp** [comment]
Cool! Thanks a lot for the support :)
