### ISSUE TITLE
Result preview title and description is URI encoded

### ISSUE THREAD

**Issue by rasmusfjord** [markwemekamp/RankOne-Umbraco-SEO-Tool#9]
If you write æøå in your description or title it becomes to this:
her er der &#230; &#248; &#229; jo

**Comment by rasmusfjord** [comment]
I tried this but its like my javascript isnt hit :
   response.Description = decodeURI(response.Description);

**Comment by rasmusfjord** [comment]
I assigned this to my new collegue he will Pull request it 🗡

**Comment by markwemekamp** [comment]
That's awesome, looking forward to it!

**Comment by markwemekamp** [comment]
Merged and I just released a new version (on our and nuget). This should be fixed now

Thanks a lot! :)
